# Generated by Django 5.2 on 2025-05-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0012_newscategory_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('business', 'Business'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_universities', to='admindashboard.userprofile'),
        ),
    ]
