# Generated by Django 5.2 on 2025-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
