# Generated by Django 5.2 on 2025-05-13 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_district_eventcategory_initiative_job_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedquestionpaper',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='approvedquestionpaper',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.degree'),
        ),
        migrations.AlterField(
            model_name='approvedquestionpaper',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
